### ISSUE TITLE
Display on Pi 5

### ISSUE THREAD

**Issue by ikjordan** [SimonGreenaway/sQLux-menu#33] opened 2024-11-02 21:46 UTC
I'm not sure that anything can be done about this, but I've raised the issue to record it:
On the latest (as of 2/11/2024) bookworm install of PiOS running on a Pi 5, the display is corrupted - see image. sQLux-menu still executes correctly. I've tried this with X11 and Wayland, both give the same issue. I've run sQLux-menu without corruption on Ubuntu24.04 LTS and Windows 10.

Fell free to shrug and close no change :-)

![pi_5](https://github.com/user-attachments/assets/e4e97d19-f4d8-4aaa-9c2a-61829eff6f0f)

**Comment by SimonGreenaway** [comment] 2024-11-02 21:54
Could you do a 'java -version' and post the response.

I've had issues with recent javas running swing on my laptop:

![image](https://github.com/user-attachments/assets/407980d5-e5b8-4ad0-8d50-25eefb610cb4)

**Comment by SimonGreenaway** [comment] 2024-11-02 21:55
(I've got a pi5 so I should be able to reproduce...)

**Comment by ikjordan** [comment] 2024-11-02 22:05
![version](https://github.com/user-attachments/assets/94d2b151-2d55-46b0-8f57-e367ccefff52)

Also I forgot to mention that the Window is fixed at top left, and as you can see, the top Title bar is missing.

**Comment by SimonGreenaway** [comment] 2024-11-02 22:11
Just tested on my pi5, same version of java - works for me, annoyingly.

**Comment by ikjordan** [comment] 2024-11-02 22:19
Have you applied the display manager changes that were rolled out this week? [A new release of Raspberry Pi OS](https://www.raspberrypi.com/news/a-new-release-of-raspberry-pi-os/) 
I have and they do seem to be in bug fixing mode now, so I wonder if that is the cause? I can try on a Pi 4 that is still running Buster tomorrow.

**Comment by SimonGreenaway** [comment] 2024-11-02 22:25
Nah, July release. I hate the way you cannot upgrade easily, it's a clean install or nothing....

**Comment by ikjordan** [comment] 2024-11-02 22:52
Works fine on a Pi4 running Bullseye (not buster as I said above, the naming convention is confusing, 3 releases beginning with B in a row!)

![pi-4](https://github.com/user-attachments/assets/6d2e4d3c-e3a8-46b4-a5d2-b10c8ac131e3)

**Comment by SimonGreenaway** [comment] 2024-11-02 22:55
So this is a raspbian upstream bug.... Phew!

**Comment by ikjordan** [comment] 2024-11-03 10:55
I did some more experiments today. The missing Title bar is due to the new labwc Window manager setting the start location off the top left. By adding a setLocation(10,10) I could see the the entire window.
I created a very simple Swing app, that rendered correctly, so perhaps the Pi update has an issue rendering tabbed displays? Anyway, I agree that this is an upstream issue.

**Comment by SimonGreenaway** [comment] 2024-11-16 17:04
Closed as upstream issue.

**Closed as not planned** 2024-11-16 17:04 UTC
